version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: library-management-system
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5433:5432"
